# kube-scheduler --config /etc/kubernetes/scheduler-extender.yaml
# https://github.com/kubernetes/kubernetes/pull/59363 (released in 1.10) we don't need to configure predicates/priorities in policy config
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
algorithmSource:
  policy:
    file:
      path: "/etc/kubernetes/scheduler-extender-policy.json"